server:
  port: 8443
  ssl:
    key-alias: domain
    key-store-type: PKCS12
    key-store: classpath:keys.p12
    key-store-password: password

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa


  jpa:
    properties:
      dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

debug: true
