version: '3.4'

services:
  demo:
    container_name: demo
    build:
      context: .
    ports:
      - 8443:8443
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:10
    ports:
    - 5432:5432

